# =========================================
# FILE: vector_db.py
# =========================================

import chromadb

CHROMA_PATH = "./chroma_storage"
COLLECTION_NAME = "indian_tax_laws"

_client = None


def get_chroma_collection():
    """
    Initializes (or reuses) a persistent ChromaDB client and returns the
    'indian_tax_laws' collection. Embeddings are NOT auto-generated by
    ChromaDB — we always pass pre-computed Gemini embeddings manually,
    so no default embedding function (e.g. sentence-transformers) is
    ever invoked or downloaded.
    """
    global _client

    if _client is None:
        _client = chromadb.PersistentClient(path=CHROMA_PATH)

    collection = _client.get_or_create_collection(name=COLLECTION_NAME)
    return collection